import "@/styles/globals.css";
import type { Metadata } from "next";

import MainHeader from "@/components/main-header";
import MainFooter from "@/components/main-footer";

import { englishFont, khmerFont } from "@/styles/font"
import ClientProvider from "@/providers/client-provider";

export const metadata: Metadata = {
  title: "Moeys Sport",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${englishFont.variable} ${khmerFont.variable}`}>
        <ClientProvider>
          <div className="flex flex-col min-h-screen dark:bg-black">
            <MainHeader />
            <main className="flex-1 overflow-hidden">
              <div className="flex flex-col gap-5">
                {children}
              </div>
              <MainFooter />
            </main>
          </div>
        </ClientProvider>
      </body>
    </html>
  );
}
