import "@/styles/globals.css";
import type { Metadata } from "next";
import { englishFont, khmerFont } from "@/styles/font"
import ClientProvider from "@/providers/client-provider";

export const metadata: Metadata = {
  title: "Moeys Sport",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${englishFont.variable} ${khmerFont.variable}`}>
        <ClientProvider>
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
